### ISSUE TITLE
Arduino Due

### ISSUE THREAD

**Issue by phhoef** [KurtE/ILI9341_t3n#39]
Is it possible to use this lib with an Arduino Due?
My first test failed, as the `DMAChannel.h` file is missing. I never saw a Teensy, but I think the file is included in the Teensy core, right?

Accordingly, it's not possible to use the lib without further ado?

**Comment by KurtE** [comment]
I would doubt that this library would work with Arduino Due.  The underlying code works directly with the hardware registers, including DMA...  

It probably could be ported but not sure how much work. 

You should be able to use the Adafruit_ili9341 library

**Comment by phhoef** [comment]
I was afraid, that you say that :-)
Thanks for your quick response.
