### ISSUE TITLE
teensy4 & HX8357 480x320

### ISSUE THREAD

**Issue by FuzzyWobble** [KurtE/ILI9341_t3n#41]
Hello. I just tested the hx8357 with a different spi tft library but only achieving 10fps. I am wondering what changes need to be made to this library to work with 4x on the HX8357 and run **very** fast (: Hopefully >40fps if possible. Thanks Kurt!

**Comment by KurtE** [comment]
Wrong library... 

Should ask in the other library... 
Which it looks like you already have: https://github.com/mjs513/HX8357_t3n/issues/5

Or ask with the other library from Adafruit
