### ISSUE TITLE
releasing this library to the Arduino Library Manager

### ISSUE THREAD

**Issue by designer2k2** [KurtE/ILI9341_t3n#43]
Hello,
first, thanks for this great library! It just works and lets me do other things, not worrying about the display :-)

Would you release it to the Arduino Library Manager?  

Looks like everything is set here so it should only need to be submitted: https://github.com/arduino/library-registry#adding-a-library-to-library-manager

The lint check mentioned there was done by me, all is ok. 

I can help making this submission if you like.

greetings from Austria,
Stephan

**Comment by KurtE** [comment]
Should be done now...

**Comment by designer2k2** [comment]
Thanks! Yes it works 👍
