### ISSUE TITLE
Error compiling examples on Arduino 1.8.5

### ISSUE THREAD

**Issue by DarkDot** [KurtE/ILI9341_t3n#6]
C:\Users\ddot\Documents\Arduino\libraries\ILI9341_t3n-master\ILI9341_t3n.cpp: In constructor 'ILI9341_t3n::ILI9341_t3n(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, SPINClass*)':

C:\Users\ddot\Documents\Arduino\libraries\ILI9341_t3n-master\ILI9341_t3n.cpp:75:27: error: 'class SPINClass' has no member named 'kinetisk_spi'

  _pkinetisk_spi = _pspin->kinetisk_spi();

                           ^

C:\Users\ddot\Documents\Arduino\libraries\ILI9341_t3n-master\ILI9341_t3n.cpp: In member function 'void ILI9341_t3n::begin()':

C:\Users\ddot\Documents\Arduino\libraries\ILI9341_t3n-master\ILI9341_t3n.cpp:1261:30: error: 'class SPINClass' has no member named 'kinetisk_spi'

     _pkinetisk_spi = _pspin->kinetisk_spi();

                              ^

C:\Users\ddot\Documents\Arduino\libraries\ILI9341_t3n-master\ILI9341_t3n.cpp:1270:31: error: 'class SPINClass' has no member named 'kinetisk_spi'

      _pkinetisk_spi = _pspin->kinetisk_spi();

                               ^

Error compiling for board Teensy 3.5.

**Comment by KurtE** [comment]
Thanks, 

I had not updated the Master branch to the newer stuff in SPIN library. So pushed up a change that should make it compile now.
